export { BareRepoFactory } from './bare_repo_factory'
export { NonBareRepoFactory } from './non_bare_repo_factory'
export * from './dugite_git_repo'
export * from './background_git_repos'
export * from './operations'
