name: Test PR

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test all packages
    runs-on: ubuntu-latest
    env:
      GIT_ROOT: /git-repos
      REDIS_URL: redis://localhost:6379
      LOGGING_READABLE_BY: humans
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: egordm/gha-yarn-node-cache@v1
      - uses: supercharge/redis-github-action@1.4.0
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Run tests in each workspace
        run: yarn test
